Cart Details #View
awesome-academy/dn_intern_tung_lai_ecommerce pull request #6
Opened 2021-11-17 09:10 UTC by laipmv-1193

2021-11-17 09:17 UTC, laipmv-1193 commented
![cart_details_view_framgia](https://user-images.githubusercontent.com/91654423/142172088-3abaf6e7-6d66-496a-adcd-6c2276886703.png)

2021-11-23 03:19 UTC, laipmv-1193 commented
ready

2021-11-23 03:33 UTC, tungnn-1192 requested changes

2021-11-23 03:33 UTC, tungnn-1192 commented on Gemfile
> -  gem "pry-rails"
tạm thời k run test nên restore cũng k khác nhau lắm lun

2021-11-23 03:33 UTC, tungnn-1192 commented on app/views/layouts/_hero.html.erb
> +                  <% if category.children.any? %>
restore cho nhẹ lun nè

2021-11-23 03:33 UTC, tungnn-1192 commented on app/views/static_pages/index.html.erb
> -
file này thay đổi k đáng kể nên định tạm thời restore file này đi cho nhẹ nè

2021-11-23 03:33 UTC, tungnn-1192 commented on app/controllers/application_controller.rb
> -
file này để fix sau cũng đc, restore cho nhẹ lun

2021-11-23 03:33 UTC, tungnn-1192 commented on app/views/layouts/_product_card.html.erb
> +            data-setbg="/img/featured/feature-1.jpg"
restore lun, sau này fix riêng lun

2021-11-23 03:33 UTC, tungnn-1192 commented on app/views/layouts/_product_carousel.html.erb
> +    <img src="/img/latest-product/lp-1.jpg" alt="" />
restore lun, sau này fix riêng lun

2021-11-23 03:57 UTC, tungnn-1192 approved these changes

2021-11-23 03:58 UTC, laipmv-1193 commented
ready

2021-11-23 07:13 UTC, vanvtt-0952 commented on app/controllers/sessions_controller.rb
> +    # binding.pry
Xóa đi cu

2021-11-23 07:13 UTC, vanvtt-0952 commented on app/controllers/sessions_controller.rb
> +  def cart_index; end
Tách hẵng ra 1 cái carts controller đi em

2021-11-23 07:13 UTC, vanvtt-0952 commented on app/helpers/sessions_helper.rb
> +  def subtotal
chị chưa hiểu cái method này lắm cu ơi

2021-11-23 07:13 UTC, vanvtt-0952 commented on app/views/sessions/cart_index.html.erb
> +	<div class="container">
indent

2021-11-23 07:13 UTC, vanvtt-0952 commented on config/routes.rb
> +    delete "/cart/remove/:id(/:all)", to: "sessions#cart_remove", as: :cart_remove
dùng resources carts đi em

2021-11-23 07:13 UTC, vanvtt-0952 commented on vendor/organi/js/main.js
> +    // var proQty = $('.pro-qty');
ko dùng thì xóa đi em

2021-11-23 07:13 UTC, vanvtt-0952 commented on app/helpers/sessions_helper.rb
> +    Product.where(id: id).pluck(attr)
where -> viết scope đi cu

2021-11-23 10:01 UTC, laipmv-1193 commented
ready

2021-11-23 10:02 UTC, laipmv-1193 commented
ready

2021-11-23 10:03 UTC, laipmv-1193 commented
ready

2021-11-23 13:51 UTC, merged