Statis Pages #Home
awesome-academy/dn_intern_tung_lai_ecommerce pull request #7
Opened 2021-11-17 09:38 UTC by laipmv-1193

## Related Tickets
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/43224)

## WHAT (optional)
- Homepage with data loaded from DB

## HOW
- Home view with partial render
- Load data: categories list, featured product, ... into Home

## WHY (optional)

## Evidence (Screenshot or Video)
![home_evidence](https://user-images.githubusercontent.com/91654423/142175547-b3d1c723-64a2-4528-8c91-98fcca9d33e0.png)

2021-11-17 09:39 UTC, laipmv-1193 commented
![home_framgia](https://user-images.githubusercontent.com/91654423/142175841-69d8ef30-7524-4398-8933-f2fc22ab62fe.png)

2021-11-17 09:55 UTC, tungnn-1192 commented
> ## Related Tickets
> * [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/43224)
## Related Tickets
- [#43224](https://edu-redmine.sun-asterisk.vn/issues/43224)

2021-11-17 10:15 UTC, tungnn-1192 requested changes

2021-11-17 10:15 UTC, tungnn-1192 commented on config/routes.rb
> +    get "/contact", to: "static_pages#contact"
mình không có 2 route này

2021-11-18 00:58 UTC, tungnn-1192 commented
ready

2021-11-18 01:54 UTC, vanvtt-0952 commented on _new = {}
> +=> [[32m#<Product:0x000055911b2f0150[0m
file j lạ thế em ơi

2021-11-18 01:54 UTC, vanvtt-0952 commented on app/helpers/categories_helper.rb
> +    Category.where parent_id: nil
`.where parent_id: nil` scope nào

2021-11-18 01:54 UTC, vanvtt-0952 commented on app/helpers/categories_helper.rb
> +    Product.order(rating: :desc).limit(max)
`.order(rating: :desc)` scope nào

2021-11-18 01:54 UTC, vanvtt-0952 commented on app/views/layouts/_hero.html.erb
> +                  <% if category.children.length > 0%>
```suggestion
                  <% if category.children.any? %>
```
chị nghĩ là ri nhỉ

2021-11-18 01:54 UTC, vanvtt-0952 commented on app/views/layouts/_product_carousel.html.erb
> +      <span><%= print_price product.price %></span>
format tiền tệ với i18n đi em

2021-11-18 02:33 UTC, tungnn-1192 commented
ready

2021-11-18 06:09 UTC, laipmv-1193 commented
ready

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/controllers/application_controller.rb
> +  end
Thêm các line trống vào e nha
```suggestion
  def default_url_options
    {locale: I18n.locale}
  end
  
  private
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
```

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/helpers/categories_helper.rb
> +      h[cat.parent.id] = cat.parent.title unless cat.parent.nil?
Nên dùng khẳng định sẽ tường minh hơn
```suggestion
  end

  def to_filters_hash products
    products.each_with_object({}) do |e, h|
      cat = e.category
      # h[cat.id] = cat.title
      h[cat.parent.id] = cat.parent.title if cat.parent.present?
```

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/helpers/sessions_helper.rb
> +  def fake_cart
method này dùng đâu e?

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/helpers/sessions_helper.rb
> +    session[:cart].keys.count
gọn code lại e
```suggestion
   session[:cart].blank? ? 0: session[:cart].keys.count    
```

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/helpers/sessions_helper.rb
> +      products_contents[pair] = Product.find_by(id: pair[0])
tìm ko thấy thì khỏi gán chứ em

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/models/product.rb
> +          all.order(rating: :desc).limit(max)
chỗ này bỏ all đi em

2021-11-18 07:04 UTC, thaodtd-0665 commented on app/helpers/categories_helper.rb
> +    Product.featured_products max
sao ở scope đã gán default max = Settings.length.featured_products.max rồi mà ở đây gọi lại phải truyền thêm max vậy nè

2021-11-18 08:04 UTC, laipmv-1193 commented
ready

2021-11-18 08:22 UTC, laipmv-1193 commented
ready

2021-11-19 08:50 UTC, vanvtt-0952 commented on app/helpers/application_helper.rb
> +    price /= Settings.rates_to.usd if I18n.locale == :en
`price /= Settings.rates_to.us` code j kì thế em

2021-11-19 13:23 UTC, tungnn-1192 commented on app/helpers/application_helper.rb
> +    price /= Settings.rates_to.usd if I18n.locale == :en
dạ là để đổi price từ vnđ theo như db sang usd chị, chỗ này em set cứng tỉ giá đổi từ usd sang vnđ vào settings.yml để đỡ gọi api nên có dòng 12 chị.

2021-11-20 04:06 UTC, merged